name: CD

on:
  release:
    types: ['created']

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Compare Package and Tag Version
        run: echo "REALEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          export VERSION=$(node -p "require('./package.json').version")
          echo $VERSION
          echo $REALEASE_VERSION
          echo ${$RELEASE_VERSION:1:5} >> $RELEASE_VERSION_PARC
          export $RELEASE_VERSION_PARC
      - name: Real Compare
        if: $VERSION != $RELEASE_VERSION_PARC
        run: exit 1
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
