name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build_ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build

  cii:
    name: Build_windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
  ciii:
    name: Build-ubuntu-latest-node-v16-and eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: esLint Auto Fix
        run: npx eslintAutoFix
      - name: esLint
        run: npm run lint
      - name: prettier
        run: npx run pret
