name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        versions: [14, 16, 18]
        include:
          - os: windows-latest
            node: 16
            npm: 6

    name: Build_and_eslint_prettier
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.versions }}
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: esLint Auto Fix
        run: npm run eslintautofix
      - name: esLint
        run: npm run lint
      - name: prettier - write
        run: npm run prettywrite
      - name: prettier - check
        run: npm run prettycheck
